# Generated by Django 3.1.5 on 2021-04-27 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_user_subscribers_+', to=settings.AUTH_USER_MODEL, verbose_name='Subscibers'),
        ),
    ]
