# Generated by Django 3.1.5 on 2021-04-27 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='video/', verbose_name='Video')),
                ('thumbnail', models.ImageField(default='/thumbnail/default.jpg', upload_to='thumbnail/')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('views', models.IntegerField(default=6758938, verbose_name='Views count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='_video_dislikes_+', to=settings.AUTH_USER_MODEL, verbose_name='Dislikes')),
                ('likes', models.ManyToManyField(blank=True, related_name='_video_likes_+', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
            ],
        ),
    ]
