"""
Django settings for youtube project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@oq^pxru&%$!4myq3ek%pquikp0%iyl12y)+r6bx4**q52+4mc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

USE_X_FORWARDED_HOST = True

FORCE_SCRIPT_NAME = ''

STATIC_SUFFIX = '/static/'
MEDIA_SUFFIX = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

try:
    # DCU CONTAINER SETTINGS
    # user.txt exist = DCU container mode
    with open(BASE_DIR / 'user.txt') as f:
        FORCE_SCRIPT_NAME = '/' + f.read()
    STATIC_ROOT = os.path.join(BASE_DIR, "static/")
    print('DCU container settings loaded')
except:
    # DEFAULT SETTINGS
    print('No user.txt file detected')
    STATIC_ROOT = os.path.join(BASE_DIR, "static/")
    # STATICFILES_DIRS = (os.path.join('static'),)
    print('Default settings loaded')

STATIC_URL = FORCE_SCRIPT_NAME + STATIC_SUFFIX
MEDIA_URL = FORCE_SCRIPT_NAME + MEDIA_SUFFIX

ALLOWED_HOSTS = [
    'containers.computing.dcu.ie',
    '127.0.0.1',
    '0.0.0.0',
    'guarded-peak-26326.herokuapp.com'
]

AUTH_USER_MODEL = 'authentication.User' 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'video.apps.VideoConfig',
    'authentication.apps.AuthenticationConfig',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'youtube.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [STATIC_ROOT, os.path.join(BASE_DIR, 'youtube/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'youtube.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/