# Generated by Django 3.1.5 on 2021-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=6625132, verbose_name='Views count'),
        ),
    ]
